name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag spc-web-gateway-to-mqtt:$(date +%s)
